os: linux

language: scala

jdk:
  - openjdk8
  - openjdk11

matrix:
  include:
  - scala: 2.11.12
    before_script:
    - sudo chmod +x /usr/local/bin/sbt
    env:
    - SCALANATIVE_VERSION="0.3.9"
    before_install:
    - sudo apt-get update
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
    script:
    - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M scoptNative/test
  - scala: 2.11.12
    before_script:
    - sudo chmod +x /usr/local/bin/sbt
    env:
    - SCALANATIVE_VERSION="0.4.0-M2"
    before_install:
    - sudo apt-get update
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
    script:
    - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M scoptNative/test

script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M scalafmtCheck test:scalafmtCheck scalafmtSbtCheck +scoptJS/test +scoptJVM/test

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete

cache:
  directories:
    - $HOME/.cache/
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/
